//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pr17Varlamov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obuvv
    {
        public int id { get; set; }
        public string Articul { get; set; }
        public string NaimObuv { get; set; }
        public string KolvoPar { get; set; }
        public string StoimostOdnoiPari { get; set; }
        public string RazmerVNalichii { get; set; }
        public string NameFabrika { get; set; }
        public Nullable<System.DateTime> SrokPostavkiObuviVMagazin { get; set; }
    }
}
